# https://help.github.com/pt/actions/reference/events-that-trigger-workflows#
# https://crontab.guru/
# Note: Had to be created on GitHub platform, else wasn't working, aparently

name: Java CI with Maven for IT

on:
  schedule:
    - cron: '0 10,15,17,20,23,01 * * *'
  push:
    branches: [ master , noRepository]
  pull_request:
    branches: [ master , noRepository]

jobs:
  i-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Integration Testing
      run: cd tqs01proj/ && mvn package failsafe:integration-test

